[cucumber] IDEA-375752 Fix PluginException when running GherkinTypingTest with the module classpath
The test has been already passing when run with the ultimate classpath.

And now, it is still failing when run with the module classpath (reason: unknown yet), but at least the PluginException is fixed.

---

Interesting stacktrace excerpts, for greppability:

ERROR: Cannot create extension (class=com.intellij.execution.testframework.TestTreeViewActionsPromoter) [Plugin: com.intellij]
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.intellij.execution.testframework.TestTreeViewActionsPromoter) [Plugin: com.intellij]

Caused by: com.intellij.diagnostic.PluginException: Cannot create extension (class=com.intellij.execution.testframework.TestTreeViewActionsPromoter) [Plugin: com.intellij] 

Caused by: java.lang.ClassNotFoundException: com.intellij.execution.testframework.TestTreeViewActionsPromoter

GitOrigin-RevId: 86758d1c49ac82ae2279d7099e0770fd7f99437d