WEB-14213 JsTestDriver: can't run tests with coverage, NoClassDefFoundError: com/google/jstestdriver/internal/guava/collect/Sets (coverage-1.3.5.jar repackaged) (cherry picked from commit 3a76c7b)