IDEA-306713: Unable to use Error Prone Compiler
Fix of IDEA-306713: Unable to use 'Error Prone Compiler' due to NoClassDefFoundError

Incorrect dataflow artifact is using, should be used dataflow-errorprone, since 3.14 version