Revert "IDEA-283892 OSGI osmorc plugin now fails in latest IDE with "java.lang.NoClassDefFoundError: aQute/bnd/osgi/Builder""
This reverts commit 9eb17e812df051d4a9bc8231d2f372feff06bbe3.

GitOrigin-RevId: 0b269ace3c5811053fc47d17fce4f66d7c4d8931