[gherkin] add dependency to org.intellij.intelliLang
IDEA-251322 java.lang.NoClassDefFoundError: org/intellij/plugins/intelliLang/inject/InjectorUtils

(cherry picked from commit 5e66c886c6772402e59c1f3c9cb9415209ff80e0)

IDEA-CR-68018

GitOrigin-RevId: ac73c515451e94e542689213ff49f9ffcee16ae2